# Generated by Django 4.1 on 2022-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorbell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='FCM Token')),
            ],
        ),
    ]
