# Generated by Django 4.1 on 2022-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorbell', '0002_clienttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rgb_color',
            field=models.CharField(max_length=8, null=True, verbose_name='RGB Color'),
        ),
        migrations.AddField(
            model_name='category',
            name='vibration_pattern',
            field=models.CharField(max_length=10, null=True, verbose_name='Vibration Pattern'),
        ),
        migrations.AddField(
            model_name='visit',
            name='num_of_confirmation',
            field=models.PositiveIntegerField(default=0, verbose_name='Number Of Confirmation'),
        ),
    ]
